#!/bin/bash/

########################Instructions for executing this script#################################
#time ./database_migration.sh
############################################################################################### 

# Script to migrate data from old database to new database

set -e
#list of tables is listed in text file
for table in $(cat table_list_v01.txt | sed '/^$/d;s/[[:blank:]]//g'); do
	
	echo $table
	
	#query to store the row count for table from old database
	mysql -h **.**.***.** -u readonly -p'*******' DatabaseName -s -N -e 'Select count(*) from '$table'' > store_count_old_instance.txt
	
	
	#Command for exporting the data
	mysqldump -h ***.**.***.** -u readonly -p'*********' --hex-blob DatabaseName $table > $table.sql
	
	
	if [ "$?" -eq "0" ]; then 
		echo "Export created successfully for "$table 
	fi
	
	#Command for Importing the data into new instance
	mysql -h 127.0.0.1 -u root DatabaseName < $table.sql
	if [ "$?" -eq "0" ]; then 
		
		#query to store the row count for imported table
		mysql -h 127.0.0.1 -u root DatabaseName -s -N -e 'Select count(*) from '$table'' > store_count_new_instance.txt
		
		cat store_count_old_instance.txt | while read cnt_old_instance; do
			echo "Row count of "$table" for old database : "$cnt_old_instance  
		done
		
		cat store_count_new_instance.txt | while read cnt_new_instance; do	
			echo "Row count of "$table" for new database : "$cnt_new_instance  
		done
		
		#Comparing the row count of Exported and Imported tables
		if [$cnt_new_instance -eq $cnt_old_instance]; then
			echo "Import created successfully for "$table
			rm $table.sql
			rm store_count_old_instance.txt
			rm store_count_new_instance.txt
		else 
			echo "Row Count does not match for Export and Import process of "$table 
		fi
	fi
	
done 
